name: Old Phone Github Action

run-name: ${{ github.actor }} is now testing my project.

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Current Path
        run: pwd
      - name: Install xunit
        run: dotnet add package xunit --version 2.9.2
        working-directory: ./OldPhoneTest
      - name: Install xunit.runner.visualstudio
        run: dotnet add package xunit.runner.visualstudio --version 2.8.2
        working-directory: ./OldPhoneTest
      - name: Install Microsoft.NET.Test.Sdk
        run: dotnet add package Microsoft.NET.Test.Sdk --version 17.12.0
        working-directory: ./OldPhoneTest
      - name: Install coverlet.collector
        run: dotnet add package coverlet.collector --version 6.0.2
        working-directory: ./OldPhoneTest
      - name: Testing...
        run: dotnet test --no-restore --logger trx --results-directory "./OldPhoneTest/TestResults-${{ matrix.dotnet-version }}"
        working-directory: ./OldPhoneTest
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: ./OldPhoneTest/TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}
        